routes/web.php
        Route::post('/polling-station/edit/{id}/post','ContentController@PollingStationEditPost')->name('PollingStationEditPost');

        Route::post('/get-electral','ContentController@getElectral')->name('getElectral');
        Route::post('/get-polling-station','ContentController@getPollingStation')->name('getPollingStation');


        Route::get('/election-type/','ElectionController@electionType')->name('electionType');
        Route::get('/election-type/add','ElectionController@newElectionType')->name('New.electionType');
        Route::post('/election-type/add','ElectionController@newElectionTypePost')->name('New.electionType');
        Route::get('/election-type/edit/{id}','ElectionController@electionTypesEdit')->name('electionTypesEdit');
        Route::post('/election-type/edit/{id}','ElectionController@electionTypesEditPost')->name('electionTypesEdit');
        Route::get('/election-type/delete/{id}','ElectionController@electionTypesDelete')->name('electionTypesDelete');

        Route::get('/political-party/','ElectionController@politicalParty')->name('politicalParty');
        Route::get('/political-party-ajax/','ElectionController@politicalPartyAjax')->name('politicalPartyAjax');
        Route::get('/political-party/add','ElectionController@newPoliticalParty')->name('New.politicalParty');
        Route::post('/political-party/add','ElectionController@newPoliticalPartyPost')->name('New.politicalParty');
        Route::get('/political-party/edit/{id?}','ElectionController@editPoliticalParty')->name('Edit.politicalParty');
        Route::post('/political-party/edit/{id}','ElectionController@editPoliticalPartyPost')->name('Edit.editPoliticalPartyPost');
        Route::get('/political-party/delete/{id?}','ElectionController@DeletePoliticalParty')->name('delete.politicalParty');

        Route::get('/candidate/{id?}','CandidateController@candidate')->name('candidate');
        Route::get('/candidate/register/{id}','CandidateController@candidateRegister')->name('candidateRegister');
        Route::post('/candidate/register/candidate','CandidateController@candidateRegisterPost')->name('candidateRegisterPost');
        Route::post('verify-positioning-ordering','CandidateController@VerifyPositioningOrdering')->name('VerifyPositioningOrdering');

        Route::get('/candidate/edit/{id?}','CandidateController@candidateEdit')->name('candidateEdit');
        Route::post('/candidate/edit/{id?}/post','CandidateController@candidateEditPost')->name('candidateEditPost');
        Route::get('/candidate/delete/{id?}','CandidateController@candidateDelete')->name('candidateDelete');


        Route::get('/election-ajax/','CandidateController@candidateAjax')->name('candidateAjax');

        Route::get('/election/','ElectionController@election')->name('election');
        Route::get('/election/new','ElectionController@electionNew')->name('electionNew');
        Route::get('/election/detail/{id}','ElectionController@electionDetail')->name('electionDetail');
        Route::post('/election/detail/{id}/post','ElectionController@electionDetailPost')->name('electionDetailPost');
        Route::post('/election/detail/post','ElectionController@electionNewPost')->name('electionNewPost');
        Route::get('/election/detail/{id}/tougle/{tougle}','ElectionController@electionDetailTougle')->name('electionDetailTougle');


    });
});


Route::group(['prefix' =>"director",'namespace'=>'Director','as' => 'Director.'], function () {
    Route::group(['middleware' => ['auth','director']], function () {
        Route::get('/election',  'AgentController@election')->name("election");
        Route::post('/election',  'AgentController@electionPost')->name("electionPost");
        Route::get('/home/{election_start_up}/{election_result_id?}/{polling_station_id?}',  'AgentController@index')->name("Home");
        Route::post('/result-capture/{election_start_up}',  'AgentController@captureResult')->name("CaptureResult");


        Route::get('/','HomeController@index')->name('home');
        Route::get('/polling-agent','PollingAgentController@pollingAgent')->name('pollingAgent');
        Route::get('/polling-agent-ajax','PollingAgentController@pollingAgentAjax')->name('pollingAgentAjax');

        Route::get('/polling-agent-edit/{id}','PollingAgentController@UsersEdit')->name('UsersEdit');
        Route::get('/polling-agent-delete/{id}','PollingAgentController@UsersDelete')->name('UsersDelete');

        Route::post('/polling-agent-edit/','PollingAgentController@EditUserPost')->name('EditUserPost');

        Route::post('/get-constituency','PollingAgentController@getConstituency')->name('getConstituency');
        Route::post('/verify-username','PollingAgentController@VerifyUsername')->name('VerifyUsername');
        Route::post('/get-regions','PollingAgentController@getRegion')->name('getRegion');
        Route::post('/get-electral','PollingAgentController@getElectral')->name('getElectral');
        Route::post('/get-polling-station','PollingAgentController@getPollingStation')->name('getPollingStation');


        Route::get('/polling-agent/{type_id}','PollingAgentController@newUser')->name('New.User');
        Route::post('/polling-agent-post','PollingAgentController@newUserPost')->name('New.UserPost');

        Route::get('/candidate/','CandidateController@candidate')->name('candidate');
        Route::get('/profile/','CandidateController@profile')->name('profile');

        Route::get('/election-ajax/','CandidateController@candidateAjax')->name('candidateAjax');

        Route::get('/candidate/register/','CandidateController@candidateRegister')->name('candidateRegister');
        Route::post('/candidate/register/candidate','CandidateController@candidateRegisterPost')->name('candidateRegisterPost');
        Route::get('/candidate/edit/{id?}','CandidateController@candidateEdit')->name('candidateEdit');
        Route::post('/candidate/edit/{id?}/post','CandidateController@candidateEditPost')->name('candidateEditPost');
        Route::get('/candidate/delete/{id?}','CandidateController@candidateDelete')->name('candidateDelete');

        Route::get('/electoral-area/','ContentController@ElectoralArea')->name('ElectoralArea');
        Route::get('/electoral-area-ajax/','ContentController@electralAajax')->name('electralAajax');
        Route::get('/electoral-area/add/','ContentController@ElectoralAreaAdd')->name('New.ElectoralArea');
        Route::post('/electoral-area/add/','ContentController@ElectoralAreaAddPost')->name('New.ElectoralArea');
        Route::get('/electoral-area/delete/{id}','ContentController@ElectoralAreaDelete')->name('ElectoralAreaDelete');
        Route::get('/electoral-area/edit/{id}','ContentController@ElectoralAreaEdit')->name('ElectoralAreaEdit');
        Route::post('/electoral-area/edit/{id}/post','ContentController@ElectoralAreaEditPost')->name('ElectoralAreaEditPost');

        Route::get('/polling-station/','ContentController@PollingStation')->name('PollingStation');
        Route::get('/polling-station-ajax/','ContentController@pollingStationAajax')->name('pollingStationAajax');
        Route::get('/polling-station/add/','ContentController@PollingStationAdd')->name('New.PollingStation');
        Route::post('/polling-station/add/','ContentController@PollingStationAddPost')->name('New.PollingStation');
        Route::get('/polling-station/delete/{id?}','ContentController@PollingStationDelete')->name('PollingStationDelete');
        Route::get('/polling-station/edit/{id?}','ContentController@PollingStationEdit')->name('PollingStationEdit');
        Route::post('/polling-station/edit/{id}/post','ContentController@PollingStationEditPost')->name('PollingStationEditPost');

        Route::post('/get-political-party','ContentController@getPoliticalParty')->name('getPoliticalParty');


        Route::get('/result','PollingAgentController@result')->name('Result');
        Route::get('/result/delete/{id}','PollingAgentController@deleteResults')->name('deleteResults');

        Route::get('/polling-station-result-ajax','PollingAgentController@pollingStationResultAajax')->name('pollingStationResultAajax');
        ///Route::get('/result/{id}','PollingAgentController@constituencyView')->name('constituencyView');
        Route::get('/view-result/{election_start_up}/{election_result_id?}',  'PollingAgentController@viewResults')->name("viewResults");
        Route::get('/confirm-result/{id}','PollingAgentController@confirmResults')->name('confirmResults');

        Route::get('/home/{election_start_up}/{election_result_id?}/{user_id?}',  'PollingAgentController@editResult')->name("editResult");
        Route::post('/result-capture/{election_start_up}/{user_id?}',  'PollingAgentController@captureResult')->name("CaptureResult");

        //        Route::get('/region-result',  'ContentController@Presidential')->name("Regional");
        Route::get('/result-xlx/{election_start_up}/{election_result_id?}',  'PollingAgentController@resultsXlx')->name("resultsXlx");

        Route::post('verify-positioning-ordering','CandidateController@VerifyPositioningOrdering')->name('VerifyPositioningOrdering');


    });
});

Route::group(['prefix' =>"region",'namespace'=>'Region','as' => 'Region.'], function () {
    Route::group(['middleware' => ['auth','region']], function () {
        Route::get('/dashboard',  'ContentController@dashboard')->name("dashboard");
        Route::get('/profile',  'ContentController@profile')->name("profile");
        Route::post('presidential-result-ajax/','ContentController@presidentialResultAjax')->name('presidentialResultAjax');
        Route::get('/region-result',  'ContentController@Presidential')->name("Regional");
        Route::get('/constituency-ajax/','ContentController@constituencyAajax')->name('constituencyAajax');
        Route::get('/constituency/result/{id}','ContentController@constituencyView')->name('constituencyView');

app/Http/Controllers/Director/HomeController.php
<?php

namespace App\Http\Controllers\Director;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Auth;
use App\Model\ElectionStartupDetail;
use App\Model\PoliticalParty;
use App\Model\ElectionResult;
use App\Model\PartyElectionResult;
use App\Model\ElectionType;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        return view("director.home.index");
    }
    public function pollingAgent(){
        return view("director.polling.index");
    }
}

resources/views/director/locations/ElectoralArea.blade.php
@extends('layouts.app_director')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-6" style=" float:  left;">
            <h3>Manage Electoral Area <small></small></h3>
        </div>
        <div class="col-md-6">
            <br>
                <a href="{{route('Director.New.ElectoralArea')}}"  style=" float:  right;" class="btn btn-success">Add New Electoral Area</a>
            </div>
    </div>



<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">



            <div class="clearfix"></div>
          </div>
          <div class="x_content ">

            <table class="table" id="table">
              <thead>
                <tr>
                    <th>ElectoralArea Name</th>

                    <th>Constituency Name</th>
                  <th>Region Name</th>
                  <th>Country Name</th>
                  <th>Total Polling Stations</th>
                  <th>Total Voter</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                 {{--  @foreach ($regions as $country)
                        <tr>

                            <td>{{$country->name}}</td>
                            <td>{{$country->constituency_name}}</td>
                            <td>{{$country->region_name}}</td>
                            <td>{{$country->country_name}}</td>
                            <td>
                                 <a href="{{route('SuperAdmin.constituencyEdit',$country->id)}}"   class="btn btn-success btn-xs">Edit</a>
                                <a href="{{route('SuperAdmin.ElectoralAreaDelete',$country->id)}}"  class="btn btn-danger btn-xs">Delete</a>
                            </td>
                        </tr>
                  @endforeach --}}


              </tbody>
            </table>

          </div>
        </div>
      </div>
</div>
</div>
@endsection

@section("script")
<script>
$('document').ready(function(){
    $('select option')
    .filter(function() {
        return !this.value || $.trim(this.value).length == 0 || $.trim(this.text).length == 0;
    })
    .remove();

$("#region_id").on('change', '', function (e) {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                }
            })
    $("#constituency_id").empty();
    var region_id = $("#region_id").val()
       // $("#username_panel").append(`<span class="fa fa-spinner"><span>` )
            var _token = $('input[name="_token"]').val();
        $.ajax({
                type: "POST",
                url: '{{route("Director.getConstituency")}}',
                data: {region_id:region_id,_token:_token},
                //dataType: "JSON",
                success: function (result) {

                    $('#constituency_id')
                            .append($("<option></option>")
                                        .attr("value","Select")
                                        .text("Select Constituency"));
                    $.each(result, function(key, value) {

                        $('#constituency_id')
                            .append($("<option></option>")
                                        .attr("value",value.id)
                                        .text(value.name));
                    });
                   }
            });
        });
        })
        </script>
         <script type="text/javascript">
            $(document).ready(function () {
               $('select option')
                       .filter(function() {
                           return !this.value || $.trim(this.value).length == 0 || $.trim(this.text).length == 0;
                       })
                       .remove();
               var data_table = $('#table').DataTable({
                   //responsive: true,
               processing: true,
               serverSide: true,
               //"iDisplayLength": 100,
               "pageLength": 10,
               "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
              stateSave: true,
               "order": [[ 1, "asc" ]],
               ajax: {url:'{!! route("Director.electralAajax") !!}',
                      data: function (d) {
                      d.status = $('#filter-status').val();
                      d.terminal = $('#filter-terminal').val();
                      if($('#constituency_id').val()){
                        d.constituency_id = $('#constituency_id').val();
                      }else {
                        d.constituency_id ="all"
                      }

                      if($('#region_id').val()){
                        d.region_id = $('#region_id').val();
                      }else{
                        d.region_id = "all"
                      }



               }},
               "columnDefs": [
                    { "searchable": false, "targets": 4 },
                    { "searchable": false, "targets": 5 }
                ],
               columns: [


                  { data: 'name', name: 'ElectoralArea.name' },
                  { data: 'constituency_name', name: 'constituency.name' },
                  { data: 'region_name', name: 'region.name' },
                  { data: 'country_name', name: 'countries.name' },
                  { data: 'total_polling', name: 'total_polling' },
                  { data: 'total_voters', name: 'total_voters' },

                  {
                   mData:null,
                   name:"id",
                     "mRender": function (data) {

           var del = "{{ route('Director.ElectoralAreaDelete',':number') }}"
                           del = del.replace(':number', data.id);

                       var url = "{{ route('Director.ElectoralAreaEdit',':number') }}";
                           url = url.replace(':number', data.id);

                       return `
                       <a style="color:white" class="btn btn-primary btn-xs" href=${url}>Edit</a>
                              <a onclick="return confirm('Delete entry?')" style="color:white" class="btn btn-danger btn-xs" href=${del}>Delete</a>
                          `;
                      }
                   }
                   ]
               });

               $('.filter').on('change', function (e) {

                   data_table.draw();
               });
               $( ".filter" ).keyup(function() {
                   data_table.draw();
               });
           });
           </script>
            <style>
                .current
                {
                    background-color: #DDD !important;
                }
            </style>

        @endsection

resources/views/director/locations/PollingStatus.blade.php
@extends('layouts.app_director')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-6" style=" float:  left;">
            <h3>Manage Polling Station <small></small></h3>
        </div>
        <div class="col-md-6">
            <br>
                <a href="{{route('Director.New.PollingStation')}}"  style=" float:  right;" class="btn btn-success">Add New Polling Station</a>
            </div>
    </div>


<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
                <select style="width:25vh; float:right" class="form-control filter" name="electoralarea_id" id="electoralarea_id"  required>

                        <option value="all" >Electral Area's (All)<option>
                            @foreach ($countries as $electionType)
                                <option value="{{$electionType->id}}"  >{{$electionType->name}}<option>
                            @endforeach
                </select>

                <br>
            <div class="clearfix"></div>
          </div>
          <div class="x_content ">

            <table class="table" id="table">
              <thead>
                <tr>
                    <th>Polling Station Id</th>
                    <th>Polling Station Name</th>
                    <th>ElectoralArea Name</th>

                    <th>Constituency Name</th>
                  <th>Region Name</th>
                  <th>Country Name</th>
                  <th>Total Voter</th>
                  <th></th>
                  {{-- <th></th> --}}
                </tr>
              </thead>
              <tbody>
                  {{-- @foreach ($regions as $country)
                        <tr>

                            <td>{{$country->polling_station_id}}</td>
                            <td>{{$country->name}}</td>
                            <td>{{$country->ElectoralArea_name}}</td>
                            <td>{{$country->constituency_name}}</td>
                            <td>{{$country->region_name}}</td>
                            <td>{{$country->country_name}}</td>
                            <td>{{$country->total_voters}}</td>
                            <td>
                                <a href="{{route('SuperAdmin.constituencyEdit',$country->id)}}"   class="btn btn-success btn-xs">Edit</a>
                                <a href="{{route('SuperAdmin.ElectoralAreaDelete',$country->id)}}"  class="btn btn-danger btn-xs">Delete</a>
                            </td>
                        </tr>
                  @endforeach --}}


              </tbody>
            </table>

          </div>
        </div>
      </div>
</div>
</div>
@endsection

@section("script")
<script>
        $('document').ready(function(){
            $('select option')
            .filter(function() {
                return !this.value || $.trim(this.value).length == 0 || $.trim(this.text).length == 0;
            })
            .remove();

        $("#region_id").on('change', '', function (e) {
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': '{{ csrf_token() }}'
                        }
                    })
            $("#constituency_id").empty();
            var region_id = $("#region_id").val()
               // $("#username_panel").append(`<span class="fa fa-spinner"><span>` )
                    var _token = $('input[name="_token"]').val();
                $.ajax({
                        type: "POST",
                        url: '{{route("Director.getConstituency")}}',
                        data: {region_id:region_id,_token:_token},
                        //dataType: "JSON",
                        success: function (result) {

                            $('#constituency_id')
                                    .append($("<option></option>")
                                                .attr("value","Select")
                                                .text("Select Constituency"));
                            $.each(result, function(key, value) {

                                $('#constituency_id')
                                    .append($("<option></option>")
                                                .attr("value",value.id)
                                                .text(value.name));
                            });
                           }
                    });
                });

                $("#constituency_id").on('change', '', function (e) {
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': '{{ csrf_token() }}'
                        }
                    })
                    $("#electoralarea_id").empty();
                    var constituency_id = $("#constituency_id").val()
                    // $("#username_panel").append(`<span class="fa fa-spinner"><span>` )
                            var _token = $('input[name="_token"]').val();
                        $.ajax({
                                type: "POST",
                                url: '{{route("Director.getElectral")}}',
                                data: {constituency_id:constituency_id,_token:_token},
                                //dataType: "JSON",
                                success: function (result) {
                                    $('#electoralarea_id')
                                            .append($("<option></option>")
                                                        .attr("value","Select")
                                                        .text("Select Electral Area"));
                                    $.each(result, function(key, value) {
                                        $('#electoralarea_id')
                                            .append($("<option></option>")
                                                        .attr("value",value.id)
                                                        .text(value.name));
                                    });
                                }
                            });
                        });
                })
                </script>

<script type="text/javascript">
    $(document).ready(function () {

       var data_table = $('#table').DataTable({
           //responsive: true,
       processing: true,
       serverSide: true,
       //"iDisplayLength": 100,
       "pageLength": 10,
       "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
      stateSave: true,
       "order": [[ 1, "asc" ]],
       ajax: {url:'{!! route("Director.pollingStationAajax") !!}',
              data: function (d) {
              d.status = $('#filter-status').val();
              d.terminal = $('#filter-terminal').val();
              if($('#constituency_id').val()){
                d.constituency_id = $('#constituency_id').val();
              }else {
                d.constituency_id ="all"
              }

              if($('#region_id').val()){
                d.region_id = $('#region_id').val();
              }else{
                d.region_id = "all"
              }
              if($('#electoralarea_id').val()){
                d.electoralarea_id = $('#electoralarea_id').val();
              }else{
                d.electoralarea_id = "all"
              }



       }},
       "columnDefs": [
                  //  { "searchable": false, "targets": 4 },
                    { "searchable": false, "targets": 5 }
                ],
       columns: [


          { data: 'polling_station_id', name: 'PollingStation.polling_station_id' },
          { data: 'name', name: 'PollingStation.name' },
            { data: 'ElectoralArea_name', name: 'ElectoralArea.name' },
            { data: 'constituency_name', name: 'constituency.name' },
            { data: 'region_name', name: 'region.name' },
            { data: 'country_name', name: 'countries.name' },
            { data: 'total_voters', name: 'PollingStation.total_voters' },


          {
           mData:null,
           name:"id",
             "mRender": function (data) {

   var del = "{{ route('Director.PollingStationDelete',':number') }}"
                   del = del.replace(':number', data.id);

               var url = "{{ route('Director.PollingStationEdit',':number') }}";
                   url = url.replace(':number', data.id);
               return `
                    <a style="color:white" class="btn btn-primary btn-xs" href=${url}>Edit</a>
                      <a style="color:white" onclick="return confirm('Delete entry?')" class="btn btn-danger btn-xs" href=${del}>Delete</a>
                  `;
              }
           }
           ]
       });

       $('.filter').on('change', function (e) {

           data_table.draw();
       });
       $( ".filter" ).keyup(function() {
           data_table.draw();
       });
   });
   </script>
    <style>
        .current
        {
            background-color: #DDD !important;
        }
    </style>

        @endsection