routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
    /*
    ==========================================================
                  Sms Api Routes
    ==========================================================
     */

        Route::any('/new-message','MessageHandler@handleNew');

     /*
    ==========================================================
            end      Sms Api Routes
    ==========================================================
     */

    Route::any('/notify_me','MessageHandler@handle');
//Route::group(['middleware' => ['auth']], function () {
    Route::get('/command', function (Request $request) {
       Artisan::call('migrate');
    });
    Route::get('/', function () {
        return redirect(route("parliment"));
    });
    Route::get('parliment/{id?}','PublicController@parliment')->name('parliment');
    Route::get('presidient/{id?}','PublicController@presidient')->name('presidient');
    Route::post('result-ajax','PublicController@ajaxResult')->name('ajaxResult');
    Route::post('result-count-ajax','PublicController@ajaxCountResult')->name('ajaxCountResult');

    Route::post('/get-constituency','PublicController@getConstituency')->name('getConstituency');
    Route::post('/get-electral','PublicController@getElectral')->name('getElectral');
    Route::post('/get-polling-station','PublicController@getPollingStation')->name('getPollingStation');
    Route::get('/presidient-graph','PublicController@result');
    Route::post('/presidient-graph-ajax','PublicController@allResultAjaxGraph')->name('allResultAjaxGraph');
    Route::get('/presidential-election-results-list','PublicController@presidentialResultList')->name('presidentialResultList');
    Route::post('get-statistics','PublicController@getStatistics')->name('getStatistics');


//});
Route::group(['middleware' => ['auth','user_type']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
});

Route::group(['prefix' =>"agent",'namespace'=>'Agent','as' => 'Agent.'], function () {
    Route::group(['middleware' => ['auth','agent']], function () {
        Route::get('/election',  'AgentController@election')->name("election");
        Route::post('/election',  'AgentController@electionPost')->name("electionPost");
        Route::get('/home/{election_start_up}/{election_result_id?}',  'AgentController@index')->name("Home");
        Route::post('/result-capture/{election_start_up}',  'AgentController@captureResult')->name("CaptureResult");
        Route::get('/results',  'AgentController@results')->name("results");
        Route::get('/view-result/{election_start_up}/{election_result_id?}',  'AgentController@viewResults')->name("viewResults");
    });
});

Auth::routes();
Route::group(['prefix' =>config('config.SuperAdminUrlPrefix'),'namespace'=>'SuperAdmin','as' => 'SuperAdmin.'], function () {

    // Authentication Routes...
    Route::get('/', function () {
        return redirect(route("SuperAdmin.login"));
    });
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');


    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['middleware' => ['auth:superAdmin']], function () {


        Route::get('/admin-users','HomeController@admin')->name('admin');
        Route::get('/admin-user/add','HomeController@newAdmin')->name('New.Admin');
        Route::get('/admin-user/edit/{id}','HomeController@editAdmin')->name('edit.Admin');
        Route::post('/admin-user/edit/{id}/post','HomeController@editAdminPost')->name('edit.AdminPost');
        Route::get('/admin-user/delete/{id}','HomeController@deleteAdmin')->name('delete.Admin');
        Route::post('/admin-user/add/post','HomeController@newAdminPost')->name('newAdminPost');


        Route::get('/','HomeController@index')->name('home');
        Route::get('/result/{id}','HomeController@result')->name('result');
        Route::get('/result/{id}/report','HomeController@resultReport')->name('resultReport');
        Route::post('/result/{id}/report/post','HomeController@resultReportPost')->name('resultReportPost');

        Route::post('presidential-result-ajax/','HomeController@presidentialResultAjax')->name('presidentialResultAjax');
        Route::post('all-result-ajax/','HomeController@allResultAjax')->name('allResultAjax');

        Route::get('/parliamentary-result','HomeController@parliamentaryResult')->name('parliamentaryResult');
        //Route::get('/parliamentary-result-ajax','HomeController@parliamentaryResultAjax')->name('parliamentaryResultAjax');
        Route::get('/constituency/result/{id}','HomeController@constituencyView')->name('constituencyView');


        Route::get('/manager-types','UserController@UserTypes')->name('UserTypes');
        Route::get('/new-manager-types','UserController@newUserTypes')->name('New.UserTypes');
        Route::get('/manager-types-edit/{id}','UserController@UserTypesEdit')->name('UserTypesEdit');
        Route::post('/manager-types-edit','UserController@UserTypesEditPost')->name('Edit.UserTypes');
        Route::get('/manager-types-delete/{id}','UserController@UserTypesDelete')->name('UserTypesDelete');

        Route::post('/new-manager-types','UserController@newUserTypesPost')->name('New.UserTypes');
        Route::get('/managers/{id?}','UserController@Users')->name('Users');
        Route::get('/new-manager/{type_id}','UserController@newUser')->name('New.User');
        Route::post('/new-manager','UserController@newUserPost')->name('New.UserPost');

        Route::post('/verify-username','UserController@VerifyUsername')->name('VerifyUsername');

        Route::get('/managers-edit/{id}','UserController@UsersEdit')->name('UsersEdit');
        Route::get('/managers-delete/{id}','UserController@UsersDelete')->name('UsersDelete');

        Route::post('/managers-edit/','UserController@EditUserPost')->name('EditUserPost');

        Route::get('/polling-agent/','UserController@pollingAgent')->name('pollingAgent');
        Route::get('/polling-agent-ajax/','UserController@pollingAgentAjax')->name('pollingAgentAjax');

        Route::get('/management-user-ajax/','UserController@managementAgentAjax')->name('managementAgentAjax');


        Route::get('/country/','ContentController@country')->name('country');
        Route::get('/country/add/','ContentController@countryAdd')->name('New.Country');
        Route::post('/country/add/','ContentController@countryAddPost')->name('New.Country');
        Route::get('/country/edit/{id}','ContentController@countryEdit')->name('countryEdit');
        Route::post('/country/edit/{id}','ContentController@countryEditPost')->name('countryEdit');
        Route::get('/country/delete/{id}','ContentController@countryDelete')->name('countryDelete');

        Route::get('/region/','ContentController@region')->name('region');
        Route::get('/region/add/','ContentController@regionAdd')->name('New.region');
        Route::post('/region/add/','ContentController@regionAddPost')->name('New.Region');
        Route::get('/region/edit/{id}','ContentController@regionEdit')->name('regionEdit');
        Route::post('/region/edit/{id}','ContentController@regionEditPost')->name('regionEdit');
        Route::get('/region/delete/{id}','ContentController@regionDelete')->name('regionDelete');

        Route::get('/constituency/','ContentController@constituency')->name('constituency');
        Route::get('/constituency-ajax/','ContentController@constituencyAajax')->name('constituencyAajax');

        Route::get('/constituency/add/','ContentController@constituencyAdd')->name('New.constituency');
        Route::post('/constituency/add/','ContentController@constituencyAddPost')->name('New.constituency');
        Route::get('/constituency/edit/{id}','ContentController@constituencyEdit')->name('constituencyEdit');
        Route::post('/constituency/edit/{id}','ContentController@constituencyEditPost')->name('constituencyEdit');
        Route::get('/constituency/delete/{id}','ContentController@constituencyDelete')->name('constituencyDelete');




        Route::post('/get-regions','ContentController@getRegion')->name('getRegion');
        Route::get('/regions-ajax','ContentController@regionAjax')->name('regionAjax');


        Route::get('/electoral-area/','ContentController@ElectoralArea')->name('ElectoralArea');
        Route::get('/electoral-area-ajax/','ContentController@electralAajax')->name('electralAajax');

        Route::get('/electoral-area/add/','ContentController@ElectoralAreaAdd')->name('New.ElectoralArea');
        Route::post('/electoral-area/add/','ContentController@ElectoralAreaAddPost')->name('New.ElectoralArea');
        /* Route::get('/electoral-area/edit/{id}','ContentController@ElectoralAreaEdit')->name('ElectoralAreaEdit');
        Route::post('/electoral-area/edit/{id}','ContentController@ElectoralAreaEditPost')->name('ElectoralAreaEdit'); */
        Route::get('/electoral-area/delete/{id}','ContentController@ElectoralAreaDelete')->name('ElectoralAreaDelete');
        Route::get('/electoral-area/edit/{id}','ContentController@ElectoralAreaEdit')->name('ElectoralAreaEdit');
        Route::post('/electoral-area/edit/{id}/post','ContentController@ElectoralAreaEditPost')->name('ElectoralAreaEditPost');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','username','user_type_id','gender','constituency','phoneno',
        "country_id",
        "region_id",
        "constituency_id","polling_station_id","electoralarea_id","added_by","secret","photo"
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];
}

resources/views/admin/user/EditUserTypes.blade.php
@extends('admin.layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-6" style=" float:  left;">
            <h3>Create New Manager Type <small> E.g Polling Agent</small></h3>
        </div>

    </div>


</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-8 col-sm-8 col-xs-8 col-md-offset-2">
        <div class="x_panel">
          <div class="x_title">
            <h2>Manager Types </h2>

            <div class="clearfix"></div>
          </div>
          <div class="x_content ">
                <form id="demo-form2" method="POST" action="{{route('SuperAdmin.Edit.UserTypes')}}" data-parsley-validate="" class="form-horizontal form-label-left" >
                        @csrf
                        <input type="hidden" name="id" value="{{$UserTypes->id}}">
                        <input type="hidden" name="oldName" value="{{$UserTypes->name}}">
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Manager Type Name <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input name="name" value="{{$UserTypes->name}}" type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3">Parent Type</label>
                            <div class="col-md-6">
                               <select class="form-control" name="parent" required>
                                <option value="0">Select</option>
                                @foreach ($AllUserTypes as $UserType)
                                    @if($UserType->id == $UserTypes->id)
                                        @continue
                                    @endif
                                   <option value="{{$UserType->id}}" @if($UserType->id == $UserTypes->parent) selected @endif>{{$UserType->name}}<option>
                                @endforeach
                              </select>
                            </div>
                          </div>


                        <div class="ln_solid"></div>
                        <div class="form-group">
                          <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button class="btn btn-primary" type="reset">Reset</button>
                            <button type="submit" class="btn btn-success">Submit</button>
                          </div>
                        </div>

                      </form>


          </div>
        </div>
      </div>
</div>
@endsection

@section("script")
<script src="{{ asset('js/bootstrap-validator/validator.min.js') }}"></script>
<script>
    $('document').ready(function(){
           $('select option')
           .filter(function() {
               return !this.value || $.trim(this.value).length == 0 || $.trim(this.text).length == 0;
           })
           .remove();


       });
</script>
        @endsection

resources/views/admin/user/NewUserTypes.blade.php
@extends('admin.layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-6" style=" float:  left;">
            <h3>Create New Manager Type <small> E.g Polling Agent</small></h3>
        </div>

    </div>


</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-8 col-sm-8 col-xs-8 col-md-offset-2">
        <div class="x_panel">
          <div class="x_title">
            <h2>Manager Types </h2>

            <div class="clearfix"></div>
          </div>
          <div class="x_content ">
                <form id="demo-form2" method="POST" action="{{route('SuperAdmin.New.UserTypes')}}" data-parsley-validate="" class="form-horizontal form-label-left" >
                        @csrf
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Manager Type Name <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input name="name" type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3">Parent Type</label>
                            <div class="col-md-6">
                               <select class="form-control" name="parent" required>
                                <option value="0">Select</option>
                                @foreach ($UserTypes as $UserType)
                                   <option value="{{$UserType->id}}">{{$UserType->name}}<option>
                                @endforeach
                              </select>
                            </div>
                          </div>


                        <div class="ln_solid"></div>
                        <div class="form-group">
                          <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button class="btn btn-primary" type="reset">Reset</button>
                            <button type="submit" class="btn btn-success">Submit</button>
                          </div>
                        </div>

                      </form>


          </div>
        </div>
      </div>
</div>
@endsection

@section("script")
<script src="{{ asset('js/bootstrap-validator/validator.min.js') }}"></script>
<script>
     $('document').ready(function(){
            $('select option')
            .filter(function() {
                return !this.value || $.trim(this.value).length == 0 || $.trim(this.text).length == 0;
            })
            .remove();


        });
</script>
        @endsection

resources/views/admin/user/UserTypes.blade.php
@extends('admin.layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-6" style=" float:  left;">
            <h3>Manager Type <small></small></h3>
        </div>
        {{-- <div class="col-md-6">
            <br>
                <a href="{{route('SuperAdmin.New.UserTypes')}}"  style=" float:  right;" class="btn btn-success">Create New Manager Type</a>
            </div> --}}
    </div>


</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-8 col-sm-8 col-xs-8 col-md-offset-2">
        <div class="x_panel">
          <div class="x_title">
            <h2>Manager Types </h2>

            <div class="clearfix"></div>
          </div>
          <div class="x_content ">

            <table class="table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Created At</th>
                </tr>
              </thead>
              <tbody>
                  @foreach ($UserTypes as $UserType)
                        <tr>
                        <th scope="row">#</th>
                            <td>{{$UserType->name}}</td>
                            <td>{{$UserType->created_at}}</td>
                            <td>
                                <a href="{{route('SuperAdmin.UserTypesEdit',$UserType->id)}}"   class="btn btn-success btn-xs">Edit</a>
                               {{--  <a href="{{route('SuperAdmin.UserTypesDelete',$UserType->id)}}"  class="btn btn-danger btn-xs">Delete</a> --}}
                            </td>
                        </tr>
                  @endforeach


              </tbody>
            </table>

          </div>
        </div>
      </div>
</div>
@endsection

@section("script")

        @endsection