routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
    /*
    ==========================================================
                  Sms Api Routes
    ==========================================================
     */

        Route::any('/new-message','MessageHandler@handleNew');

     /*
    ==========================================================
            end      Sms Api Routes
    ==========================================================
     */

    Route::any('/notify_me','MessageHandler@handle');
//Route::group(['middleware' => ['auth']], function () {
    Route::get('/command', function (Request $request) {
       Artisan::call('migrate');
    });
    Route::get('/', function () {
        return redirect(route("parliment"));
    });
    Route::get('parliment/{id?}','PublicController@parliment')->name('parliment');
    Route::get('presidient/{id?}','PublicController@presidient')->name('presidient');
    Route::post('result-ajax','PublicController@ajaxResult')->name('ajaxResult');
    Route::post('result-count-ajax','PublicController@ajaxCountResult')->name('ajaxCountResult');

    Route::post('/get-constituency','PublicController@getConstituency')->name('getConstituency');
    Route::post('/get-electral','PublicController@getElectral')->name('getElectral');
    Route::post('/get-polling-station','PublicController@getPollingStation')->name('getPollingStation');
    Route::get('/presidient-graph','PublicController@result');
    Route::post('/presidient-graph-ajax','PublicController@allResultAjaxGraph')->name('allResultAjaxGraph');
    Route::get('/presidential-election-results-list','PublicController@presidentialResultList')->name('presidentialResultList');
    Route::post('get-statistics','PublicController@getStatistics')->name('getStatistics');


//});
Route::group(['middleware' => ['auth','user_type']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
});

Route::group(['prefix' =>"agent",'namespace'=>'Agent','as' => 'Agent.'], function () {
    Route::group(['middleware' => ['auth','agent']], function () {
        Route::get('/election',  'AgentController@election')->name("election");
        Route::post('/election',  'AgentController@electionPost')->name("electionPost");
        Route::get('/home/{election_start_up}/{election_result_id?}',  'AgentController@index')->name("Home");
        Route::post('/result-capture/{election_start_up}',  'AgentController@captureResult')->name("CaptureResult");
        Route::get('/results',  'AgentController@results')->name("results");
        Route::get('/view-result/{election_start_up}/{election_result_id?}',  'AgentController@viewResults')->name("viewResults");
    });
});

Auth::routes();
Route::group(['prefix' =>config('config.SuperAdminUrlPrefix'),'namespace'=>'SuperAdmin','as' => 'SuperAdmin.'], function () {

    // Authentication Routes...
    Route::get('/', function () {
        return redirect(route("SuperAdmin.login"));
    });
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');


    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['middleware' => ['auth:superAdmin']], function () {


        Route::get('/admin-users','HomeController@admin')->name('admin');
        Route::get('/admin-user/add','HomeController@newAdmin')->name('New.Admin');
        Route::get('/admin-user/edit/{id}','HomeController@editAdmin')->name('edit.Admin');
        Route::post('/admin-user/edit/{id}/post','HomeController@editAdminPost')->name('edit.AdminPost');
        Route::get('/admin-user/delete/{id}','HomeController@deleteAdmin')->name('delete.Admin');
        Route::post('/admin-user/add/post','HomeController@newAdminPost')->name('newAdminPost');


        Route::get('/','HomeController@index')->name('home');
        Route::get('/result/{id}','HomeController@result')->name('result');
        Route::get('/result/{id}/report','HomeController@resultReport')->name('resultReport');
        Route::post('/result/{id}/report/post','HomeController@resultReportPost')->name('resultReportPost');

        Route::post('presidential-result-ajax/','HomeController@presidentialResultAjax')->name('presidentialResultAjax');
        Route::post('all-result-ajax/','HomeController@allResultAjax')->name('allResultAjax');

        Route::get('/parliamentary-result','HomeController@parliamentaryResult')->name('parliamentaryResult');
        //Route::get('/parliamentary-result-ajax','HomeController@parliamentaryResultAjax')->name('parliamentaryResultAjax');
        Route::get('/constituency/result/{id}','HomeController@constituencyView')->name('constituencyView');


        Route::get('/manager-types','UserController@UserTypes')->name('UserTypes');
        Route::get('/new-manager-types','UserController@newUserTypes')->name('New.UserTypes');
        Route::get('/manager-types-edit/{id}','UserController@UserTypesEdit')->name('UserTypesEdit');
        Route::post('/manager-types-edit','UserController@UserTypesEditPost')->name('Edit.UserTypes');
        Route::get('/manager-types-delete/{id}','UserController@UserTypesDelete')->name('UserTypesDelete');

        Route::post('/new-manager-types','UserController@newUserTypesPost')->name('New.UserTypes');
        Route::get('/managers/{id?}','UserController@Users')->name('Users');
        Route::get('/new-manager/{type_id}','UserController@newUser')->name('New.User');
        Route::post('/new-manager','UserController@newUserPost')->name('New.UserPost');

        Route::post('/verify-username','UserController@VerifyUsername')->name('VerifyUsername');

        Route::get('/managers-edit/{id}','UserController@UsersEdit')->name('UsersEdit');
        Route::get('/managers-delete/{id}','UserController@UsersDelete')->name('UsersDelete');

        Route::post('/managers-edit/','UserController@EditUserPost')->name('EditUserPost');

        Route::get('/polling-agent/','UserController@pollingAgent')->name('pollingAgent');
        Route::get('/polling-agent-ajax/','UserController@pollingAgentAjax')->name('pollingAgentAjax');

        Route::get('/management-user-ajax/','UserController@managementAgentAjax')->name('managementAgentAjax');


        Route::get('/country/','ContentController@country')->name('country');
        Route::get('/country/add/','ContentController@countryAdd')->name('New.Country');
        Route::post('/country/add/','ContentController@countryAddPost')->name('New.Country');
        Route::get('/country/edit/{id}','ContentController@countryEdit')->name('countryEdit');
        Route::post('/country/edit/{id}','ContentController@countryEditPost')->name('countryEdit');
        Route::get('/country/delete/{id}','ContentController@countryDelete')->name('countryDelete');

        Route::get('/region/','ContentController@region')->name('region');
        Route::get('/region/add/','ContentController@regionAdd')->name('New.region');
        Route::post('/region/add/','ContentController@regionAddPost')->name('New.Region');
        Route::get('/region/edit/{id}','ContentController@regionEdit')->name('regionEdit');
        Route::post('/region/edit/{id}','ContentController@regionEditPost')->name('regionEdit');
        Route::get('/region/delete/{id}','ContentController@regionDelete')->name('regionDelete');

        Route::get('/constituency/','ContentController@constituency')->name('constituency');
        Route::get('/constituency-ajax/','ContentController@constituencyAajax')->name('constituencyAajax');

        Route::get('/constituency/add/','ContentController@constituencyAdd')->name('New.constituency');
        Route::post('/constituency/add/','ContentController@constituencyAddPost')->name('New.constituency');
        Route::get('/constituency/edit/{id}','ContentController@constituencyEdit')->name('constituencyEdit');
        Route::post('/constituency/edit/{id}','ContentController@constituencyEditPost')->name('constituencyEdit');
        Route::get('/constituency/delete/{id}','ContentController@constituencyDelete')->name('constituencyDelete');




        Route::post('/get-regions','ContentController@getRegion')->name('getRegion');
        Route::get('/regions-ajax','ContentController@regionAjax')->name('regionAjax');


        Route::get('/electoral-area/','ContentController@ElectoralArea')->name('ElectoralArea');
        Route::get('/electoral-area-ajax/','ContentController@electralAajax')->name('electralAajax');

        Route::get('/electoral-area/add/','ContentController@ElectoralAreaAdd')->name('New.ElectoralArea');
        Route::post('/electoral-area/add/','ContentController@ElectoralAreaAddPost')->name('New.ElectoralArea');
        /* Route::get('/electoral-area/edit/{id}','ContentController@ElectoralAreaEdit')->name('ElectoralAreaEdit');
        Route::post('/electoral-area/edit/{id}','ContentController@ElectoralAreaEditPost')->name('ElectoralAreaEdit'); */
        Route::get('/electoral-area/delete/{id}','ContentController@ElectoralAreaDelete')->name('ElectoralAreaDelete');
        Route::get('/electoral-area/edit/{id}','ContentController@ElectoralAreaEdit')->name('ElectoralAreaEdit');
        Route::post('/electoral-area/edit/{id}/post','ContentController@ElectoralAreaEditPost')->name('ElectoralAreaEditPost');

app/Http/Controllers/Director/HomeController.php
<?php

namespace App\Http\Controllers\Director;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Auth;
use App\Model\ElectionStartupDetail;
use App\Model\PoliticalParty;
use App\Model\ElectionResult;
use App\Model\PartyElectionResult;
use App\Model\ElectionType;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        return view("director.home.index");
    }
    public function pollingAgent(){
        return view("director.polling.index");
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/agent/home/election.blade.php
@extends('layouts.app_agent')
@section('content')

    <form action="{{route('Agent.electionPost')}}" method="POST" id="terminal-form" class="form-horizontal form-label-left input_mask">
        @csrf
        <div >
            <br>
                <div class="container-fluid">

                    <div class="row">

                        <div class="col-md-12">
                            <div class="panel" style="background-color: aliceblue;">
                                <div class="panel-heading">

                                </div>
                                <div class="panel-body">
                                        <div class="col-md-4">
                                          Update Result for Election
                                        </div>
                                        <div class="col-md-6">
                                                <select class="form-control" name="election_start_update">
                                                        <option value="">Choose</option>
                                                        @foreach ($electionStartupDetail as $electionStartup)
                                                            <option value="{{$electionStartup->id}}">{{$electionStartup->election_name}} -- {{$electionStartup->name}}</option>
                                                        @endforeach
                                                    </select>
                                        </div>
                                        <div class="col-md-2">
                                        </div>

                                        <div class="col-md-12">
                                                <br>
                                            </div>
                                        <div class="col-md-4">

                                            </div>
                                            <div class="col-md-6">
                                                    <div class="form-group">
                                                            <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-4">
                                                               <button id="reset" class="btn btn-primary" type="reset">Reset</button>
                                                                <button id="submit" type="submit" class="btn btn-success"> <i id="submitIcon"> </i> Submit</button>
                                                            </div>
                                                        </div>
                                            </div>
                                            <div class="col-md-2">
                                            </div>



                                </div>
                            </div>
                        </div>



                    </div>

                </div>

            </div>
        </form>




@endsection
@section('script')
@endsection

resources/views/agent/home/results.blade.php
@extends('layouts.app_agent')
@section('content')


                <div class="container-fluid">
                        <br>
                        <div class="row">

                        <div class="col-md-12">
                            <div class="panel" >
                                <div class="panel-heading">

                                </div>
                                <div class="panel-body">
                                        <div class="col-md-12">
                                                <br>
                                                <table class="table table-striped">
                                                        <thead>
                                                          <tr>
                                                            <th>Election Name</th>
                                                            <th>Election Type</th>
                                                            <th>Registered Voters</th>
                                                            <th>Valid Votes</th>
                                                            <th >Over Voting</th>
                                                            <th></th>
                                                          </tr>
                                                        </thead>
                                                        <tbody>
                                                                @foreach ($electionResults as $electionResult)
                                                          <tr>
                                                            <td>  {{$electionResult->election_name}}</td>
                                                            <td>  {{$electionResult->election_type_name}}</td>
                                                            <td>  {{number_format($electionResult->total_voters)}}</td>
                                                            <td>  {{number_format($electionResult->obtained_votes)}}</td>

                                                                @if(($electionResult->total_ballot - $electionResult->total_voters)!=0 && ($electionResult->total_ballot > $electionResult->total_voters))
                                                                    <td class="fa fa-close" style="color:red"> {{number_format($electionResult->total_ballot-$electionResult->total_voters)}} </td>
                                                                @else
                                                                    <td> <span class="fa fa-check-square-o" style="color:green;font-size:16px"> No </span></td>
                                                                @endif


                                                            <td>
                                                                    <a style="color:white"  href="{{route('Agent.viewResults',[$electionResult->election_start_up_id,$electionResult->id])}}"> <span class="fa fa-eye" style="color:#0000CD"title="View Results"> </span></a>

                                                                @if($electionResult->verify_by_constituency !=1)

                                                                    <a style="color:white"  href="{{route('Agent.Home',[$electionResult->election_start_up_id,$electionResult->id])}}"> <span class="fa fa-edit" style="color:#FF4500"title="Edit/Update Results"> </span></a>
                                                                @endif
                                                            </td>
                                                          </tr>
                                                          @endforeach
                                                        </tbody>
                                                      </table>
                                            </div>
                                   {{--  @foreach ($electionResults as $electionResult)
                                        <div class="col-md-4">

                                        </div>
                                        <div class="col-md-4">

                                        </div>
                                        <div class="col-md-4">

                                        </div>
                                    @endforeach --}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>





@endsection
@section('script')
<style>
    td {
   /* padding:0 !important; margin:0 !important;
   line-height: 4px */

}
</style>
@endsection

resources/views/agent/home/viewResults.blade.php
@extends('layouts.app_agent')
@section('content')


        <!-- MAIN CONTENT -->
         <div >
                <div class="container-fluid">
                    <br>
                    <h3 class="page-title">Result Detail</h3>
                    <div class="row">

                        <div class="col-md-12">
                            <div class="panel" style="background-color: aliceblue;">
                                <div class="panel-heading">
                                    <h1 class="panel-title"><strong>My Polling Station Detail</strong></h1>
                                </div>
                                <div class="panel-body">
                                        <div class="col-md-4">
                                                <strong> Election  : </strong> {{$electionStartupDetail->election_name}}
                                        </div>
                                        <div class="col-md-4">
                                                <strong>Election Type : </strong>{{$electionStartupDetail->name}}
                                        </div>
                                        <div class="col-md-4">
                                        </div>
                                        <div class="col-md-12">
                                            <br>
                                        </div>

                                        <div class="col-md-4">
                                                <strong> Loged In as : </strong> {{$user->user_type_name}}
                                        </div>
                                        <div class="col-md-4">
                                                <strong>Polling Station Name : </strong>{{$user->PollingStation_name}}
                                        </div>
                                        <div class="col-md-4">
                                                <strong>Polling Station Code : </strong> {{$user->PollingStation_Id}}
                                        </div>
                                        <div class="col-md-12">
                                            <br>
                                        </div>
                                        <div class="col-md-4">
                                                <strong> Region : </strong> {{$user->region_name}}
                                        </div>
                                        <div class="col-md-4">
                                                <strong>Constituency : </strong>{{$user->constituency_name}}
                                        </div>
                                        <div class="col-md-4">
                                                <strong>Electoral Area  : </strong> {{$user->ElectoralArea_name}}
                                        </div>
                                </div>
                            </div>
                        </div>

                            <div class="col-md-12">
                                    <div class="panel">
                                        {{-- <div class="panel-heading">
                                            <h3 class="panel-title">Details</h3>
                                        </div> --}}
                                        <div class="panel-body" style="border: 6px solid #f1f8ff">

                                                <div class="col-md-4">
                                                        <strong>Name Of Candidate</strong>
                                                </div>
                                                <div class="col-md-4">
                                                        <strong>Party Initial</strong>
                                                </div>
                                                <div class="col-md-4">
                                                        <strong>Votes Obtained </strong>
                                                </div>
                                                <div class="col-md-12">
                                                    <br>
                                                </div>
                                                @if($electionResult && isset($electionResult) && count($electionResult)!=0)
                                                    @foreach($electionResult as $_electionResult)
                                                    <div class="col-md-12">
                                                            <div class="col-md-4">
                                                                    <strong>{{$_electionResult->first_name}} {{$_electionResult->last_name}}</strong>
                                                            </div>
                                                            <div class="col-md-4">
                                                                    <strong>{{$_electionResult->party_initial}}</strong>
                                                            </div>
                                                            <div class="col-md-4">
                                                                    <div class="form-group">
                                                                            <label>
                                                                    {{$_electionResult->party_election_result_obtained_vote}}

                                                                            </label>

                                                                            <div class="help-block with-errors"></div>
                                                                        </div>
                                                            </div>
                                                    </div>
                                                    @endforeach

                                                    <div class="col-md-12">

                                                            <div class="col-md-4">
                                                                    <div class="form-group">
                                                                            <label>Rejected Vote</label>
                                                                           <p style="background: aliceblue;text-align: center;"> {{$electionResult->toArray()[0]['total_rejected_ballot']}}</p>
                                                                            <div class="help-block with-errors"></div>
                                                                        </div>
                                                            </div>
                                                            <div class="col-md-4">

                                                            </div>
                                                            <div class="col-md-4">
                                                                    <div class="form-group">
                                                                            <label>Obtained Votes</label>
                                                                            <p style="background: aliceblue;text-align: center;"> {{$electionResult->toArray()[0]['obtained_votes']}}</p>

                                                                            <div class="help-block with-errors"></div>
                                                                        </div>
                                                            </div>

                                                    </div>
                                                    <div class="col-md-12">
                                                            <div class="col-md-4">

                                                                </div>
                                                            <div class="col-md-4">
                                                                    <div class="form-group">
                                                                            <label>Total Votes at Polling Station</label>
                                                                            <p style="background: aliceblue;text-align: center;"> {{$electionResult->toArray()[0]['total_ballot']}}</p>

                                                                            <div class="help-block with-errors"></div>
                                                                        </div>
                                                            </div>


                                                    </div>
                                                @else

                                                @endif






                                        </div>

                                    </div>
                            </div>

                    </div>
                    <!-- end new -->
                    <!-- new 1 -->

                </div>
                <!-- end new 1 -->
                <!-- new 1 -->

            </div>





@endsection
@section('script')
@endsection